name: test_unictive
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_staggered_grid_view: ^0.7.0
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  http_api_service: ^1.0.4
  hydrated_bloc: ^10.0.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
